apiVersion: v1
kind: Service
metadata:
  name: myapp1
  labels:
    name: myapp1
    app: myapp1
spec:
  type: NodePort
  ports:
  - port: 8080
    name: porta2
    protocol: TCP
    nodePort: 31888
    targetPort: 8080
  selector:
    app:  myapp1
